---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: apic
  connection: local
  gather_facts: False
  vars_prompt:
    - name: "tenant"
      prompt: "What would you like to name your Tenant?"
      private: no
    - name: "vrf"
      prompt: "What would you like to name your VRF?"
      private: no

  vars:
    ext_epg_subnets:
    - 200.123.10.0/24
    - 200.123.20.0/24

  tasks:
    - name: TASK 0A - Ensure Tenant exist
      aci_tenant:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        name_alias: "ansible_test_tenant"
        description: "Tenant Created Using Ansible by jcostavi"

    - name: TASK 0B - Ensure VRF exist
      aci_vrf:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        vrf: "{{ vrf }}"
        description: "VRF Created Using Ansible"

    - name: TASK 1A - Add a new L3Out
      aci_l3out:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: False
        tenant: "{{ tenant }}"
        name: "prod_l3out"
        description: "L3Out for Production tenant"
        domain: "L3_DOM_LAB"
        vrf: "{{ vrf }}"
        l3protocol: bgp

    - name: TASK 2A - Add a new External-Epg
      aci_l3out_extepg:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: False
        tenant: "{{ tenant }}"
        l3out: "prod_l3out"
        name: "prod_extepg"
        description: "ExtEpg for Production L3Out"
        contract_exception_tag: test
        qos_class: level6
        route_control_profiles:
          import_profile: test1
          export_profile: test2

    - name: TASK 2B - Add a new External Subnet
      cisco.aci.aci_l3out_extsubnet:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: False
        tenant: "{{ tenant }}"
        l3out: "prod_l3out"
        extepg: "prod_extepg"
        description: External Subnet for Production ExtEpg
        network: "{{ item }}"
        scope: 
         - export-rtctrl
         - import-security
      with_items: "{{ ext_epg_subnets }}"

    - name: TASK 2C - Bind a contract to an external EPG
      cisco.aci.aci_l3out_extepg_to_contract:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: False
        tenant: "{{ tenant }}"
        l3out: "prod_l3out"
        extepg : "prod_extepg"
        contract: "default"
        contract_type: provider

    - name: TASK 3A - Add a new node profile
      cisco.aci.aci_l3out_logical_node_profile:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: False
        tenant: "{{ tenant }}"
        l3out: "prod_l3out"
        node_profile: "my_node_profile"
        description: node profile for my_l3out
        dscp: CS0
        

    - name: TASK 3B - Add a new node to a node profile
      cisco.aci.aci_l3out_logical_node:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: False
        tenant: "{{ tenant }}"
        l3out: "prod_l3out"
        node_profile: my_node_profile
        pod_id: 1
        node_id: 101
        router_id: 10.101.101.101
        loopback_address: 10.101.101.101

    - name: TASK 4A -Add a new interface profile
      cisco.aci.aci_l3out_logical_interface_profile:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: False
        tenant: "{{ tenant }}"
        l3out: "prod_l3out"
        node_profile: my_node_profile
        interface_profile: "my_interface_profile"

    - name: TASK 4B - Add a new SVI physical port
      cisco.aci.aci_l3out_interface:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: False
        tenant: "{{ tenant }}"
        l3out: "prod_l3out"
        node_profile: my_node_profile
        interface_profile: my_interface_profile
        pod_id: 1
        node_id: 101
        path_ep: eth1/2
        interface_type: ext-svi
        address: 192.168.10.1/24
        encap: vlan-501
        mode: regular

    - name: TASK 5A -Add BGP Peer to the Node Profile level
      cisco.aci.aci_l3out_bgp_peer:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: False
        tenant: "{{ tenant }}"
        l3out: "prod_l3out"
        node_profile: my_node_profile
        peer_ip: 10.10.5.5
        remote_asn: 65120
        ttl: 4
        bgp_controls:
          - nh-self
          - send-com
          - send-ext-com
        route_control_profiles:
          - tenant: "ansible_tenant"
            profile: "anstest_import"
            direction: "import"
          - tenant: "ansible_tenant"
            profile: "anstest_export"
            direction: "export"
            l3out: "anstest_l3out"

    - name: TASK 5B -Create static routes
      cisco.aci.aci_l3out_static_routes:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: False
        tenant: "{{ tenant }}"
        l3out: "prod_l3out"
        logical_node: my_node_profile
        pod_id: 1
        node_id: 101
        prefix: 10.10.5.5/32
        description: "Route to IP from Peer BGP Loopback"

    - name: TASK 5C -Add a new nexthop to a prefix
      cisco.aci.aci_l3out_static_routes_nexthop:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: False
        tenant: "{{ tenant }}"
        l3out: "prod_l3out"
        node_profile: my_node_profile
        pod_id: 1
        node_id: 101
        prefix: 10.10.5.5/32
        nexthop: 192.168.10.2
        
        
        
        

